### ISSUE TITLE
can't seem to read extentions-fileds from compose 3.4

### ISSUE THREAD

**Issue by bjuergens** [compose-viz/compose-viz#48]
I have a big compose file, where I reuse some nodes by using extention fields, which ocmpose-viz doesn't seem to like very much

here is a minimal example to reproduce the issue:

```bash
> cat docker-compose.yml

x-backend: &backend_base
  image: debian:11

version: '3'
services:
  backend:
    <<: *backend_base
    ports:
      - "13000:3000"
    profiles: ["deploy"]
  backend_integration:
    <<: *backend_base
    profiles: ["integration"]
    environment:
      - KEYCLOAK_URL=http://keycloak_integration:8180/auth%                                                                                                                      


> docker compose --profile deploy config

name: test123123
services:
  backend:
    profiles:
    - deploy
    image: debian:11
    networks:
      default: null
    ports:
    - mode: ingress
      target: 3000
      published: "13000"
      protocol: tcp
networks:
  default:
    name: test123123_default
x-backend:
  image: debian:11


> docker run --rm -it -v $(pwd):/in wst24365888/compose-viz -m png docker-compose.yml

Traceback (most recent call last):
  File "compose_viz/parser.py", line 43, in parse
  File "pydantic_yaml/mixin.py", line 244, in parse_file
  File "pydantic_yaml/mixin.py", line 215, in parse_raw
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ComposeSpecification
x-backend
  extra fields not permitted (type=value_error.extra)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compose_viz/__main__.py", line 4, in <module>
  File "compose_viz/cli.py", line 66, in start_cli
  File "typer/main.py", line 214, in __call__
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1635, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "typer/main.py", line 532, in wrapper
  File "compose_viz/cli.py", line 55, in compose_viz
  File "compose_viz/parser.py", line 45, in parse
RuntimeError: Error parsing file 'docker-compose.yml': 1 validation error for ComposeSpecification
x-backend
  extra fields not permitted (type=value_error.extra)
[7] Failed to execute script '__main__' due to unhandled exception!


```

On a side note: I also use profiles, which could also be part of the problem? idk. 

for extension-fields see: https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields

for profiles see: https://docs.docker.com/compose/compose-file/compose-file-v3/#profiles

**Comment by wst24365888** [comment]
Hi @bjuergens, we've fixed this and released version 0.3.1, thanks for the report!
